server: 
  port: 9003
spring: 
  application:  
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 192.168.25.128
      database: spitdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/