server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.128:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.128
  rabbitmq:
    host: 192.168.25.128
jwt:
  config:
    num: 86400000
    key: itcast
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/