server: 
  port: 9011
spring: 
  application:  
    name: tensquare-manager #指定服务名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
feign:
  hystrix:
    enable: true
#设置路由转发的规则
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base