server:
  port: 12000
spring:
  application:
    name: tensquare_config

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chuanzhiliubei/tensquare‐config.git
#配置啦eureka的客户端
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus‐refresh