server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.128:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.25.133:6878/eureka/
feign:
  hystrix:
    enable: true